using System.Collections.Generic;

using System.Linq;
using GameDatabase.DataModel;
using GameDatabase.Model;

namespace Database.Legacy
{
    public static class LegacyShipNames
    {
        public static ItemId<Ship> GetId(string value) { int id; return new ItemId<Ship>(_items.TryGetValue(value, out id) ? id : -1); }

        public static string GetName(ItemId<Ship> id) { return _items.FirstOrDefault(item => item.Value == id.Value).Key; } // TODO: delete

        private static readonly Dictionary<string, int> _items = new Dictionary<string, int>()
        {
            { "Boss0", 1 },
            { "Boss1", 2 },
            { "Boss2", 3 },
            { "Boss3", 4 },
            { "Boss4", 5 },
            { "Boss5", 6 },
            { "Boss6", 7 },
            { "Boss7", 8 },
            { "Boss8", 9 },
            { "Boss9", 10 },
            { "Bossa", 11 },
            { "f0s1", 12 },
            { "f0s1_mk2", 13 },
            { "f0s2", 14 },
            { "f0s3", 15 },
            { "f0s4", 16 },
            { "f1s1", 17 },
            { "f1s1_mk2", 18 },
            { "f1s2", 19 },
            { "f1s3", 20 },
            { "f1s4", 21 },
            { "f1s5", 22 },
            { "f2s1", 23 },
            { "f2s1_mk2", 24 },
            { "f2s2", 25 },
            { "f2s3", 26 },
            { "f2s4", 27 },
            { "f2s5", 28 },
            { "f3s1", 29 },
            { "f3s1_mk2", 30 },
            { "f3s2", 31 },
            { "f3s3", 32 },
            { "f3s4", 33 },
            { "f4s1", 34 },
            { "f4s1_mk2", 35 },
            { "f4s2", 36 },
            { "f4s3", 37 },
            { "f4s4", 38 },
            { "f5s1", 39 },
            { "f5s1_mk2", 40 },
            { "f5s2", 41 },
            { "f5s3", 42 },
            { "f5s4", 43 },
            { "f6s1", 44 },
            { "f6s1_mk2", 45 },
            { "f6s2", 46 },
            { "f6s3", 47 },
            { "f6s4", 48 },
            { "f6s5", 49 },
            { "f7s1", 50 },
            { "f7s1_mk2", 51 },
            { "f7s2", 52 },
            { "f7s3", 53 },
            { "f7s4", 54 },
            { "f8s1", 55 },
            { "f8s2", 56 },
            { "f8s3", 57 },
            { "f8s4", 58 },
            { "f9s1", 59 },
            { "f9s2", 60 },
            { "f9s3", 61 },
            { "f9s4", 62 },
            { "f9s5", 63 },
            { "fas1", 64 },
            { "fas2", 65 },
            { "fas3", 66 },
            { "fas3_mk2", 67 },
            { "fas4", 68 },
            { "fns1", 69 },
            { "fns2", 70 },
            { "fns3", 71 },
            { "fns3_mk2", 72 },
            { "fns4", 73 },
            { "fns5", 74 },
            { "fns6", 75 },
            { "fns7", 76 },
            { "fns8", 77 },
            { "fns9", 78 },
            { "Invader1", 79 },
            { "Invader2", 80 },
            { "Invader_pirate", 81 },
            { "Invader_test", 82 },
            { "mothership", 83 },
            { "MyInvader", 84 },
            { "11", 85 },
            { "21", 86 },
            { "22", 87 },
            { "31", 88 },
            { "41", 89 },
            { "51", 90 },
            { "81", 91 },
            { "91", 92 },
            { "a1", 93 },
            { "starbase", 94 },
        };
    }
}
